#! /bin/bash

temp_file="/home/garage_monitor/Garage-Door-Monitor/data/tempfile.log"
new_month=$(date +%Y%m)
previous_month=$(date -d "$(date) - 1 months" +%Y-%m)

hist_file="/home/garage_monitor/Garage-Door-Monitor/data/garage_door_status_history.log"
hist_file_base=${hist_file%.*}

archive_file=$hist_file_base"_"$previous_month".log"

# Rename current file to archive file if archive file doesn't exist
if [ -f "$archive_file" ]; then
  date_str=$(date +%Y-%m-%d) $(date +%H:%M:%S,%03N)
  logfile="/home/garage_monitor/Garage-Door-Monitor/logs/logfile.log"
  echo $date_str":INFO:The file '$archive_file' exists. Don't archive" >> $logfile
else
  mv $hist_file $archive_file
fi
