#!/bin/bash

/home/garage_monitor/Garage-Door-Monitor/scr/scripts/stop_garage_door_monitor

# Sometimes start fails due to DigitalInputDevide initiation failue.
# It usually works the second time. This mentod gives it 5 seconds to start
# then tries again if it didn't start

cd /home/garage_monitor/Garage-Door-Monitor
source /home/garage_monitor/Garage-Door-Monitor/.env/bin/activate

while [ $(pidof "/home/garage_monitor/python/bin/python" | wc -w) -ne 1 ]
do
  /home/garage_monitor/python/bin/python -m src.garage_door_status_monitor &
  sleep 5
done
