

base:
    APP:  # Window Start-up
        LOOP_DELAY: 60

    LOGGING:
        CONFIG_PATH: "configs/logging_config.yaml"

    DOORS:
        TWO_CAR:
            CLOSED:
                NUMBER: 5
                PULL_UP: True
                BOUNCE_TIME: 1.0
            OPEN:
                NUMBER: 6
                PULL_UP: True
                BOUNCE_TIME: 1.0
                TIME_LIMIT: 5  # minutes
                ALARM_SPACING: 5  # minutes
        ONE_CAR:
            CLOSED:
                NUMBER: 13
                PULL_UP: True
                BOUNCE_TIME: 1.0
            OPEN:
                NUMBER: 0
                PULL_UP: True
                BOUNCE_TIME: 1.0
                TIME_LIMIT: 10  # minutes
                ALARM_SPACING: 5  # minutes

dev:
    BLANK: 0
