base:
    APP:  # Window Start-up
        LOOP_DELAY: 15  # seconds
        DOOR_MIDSTATE_RE_EVAL_TIME: 30  # seconds

    LOGGING:
        CONFIG_PATH: "configs/logging_config.yaml"

    GRAPHING:
        MAX_TRANSITION_TIME: 60  # seconds

    DOORS:
        TWO_CAR:
            CLOSED:
                NUMBER: 5
                PULL_UP: True
                BOUNCE_TIME: 1.0
            OPEN:
                NUMBER: 6
                PULL_UP: True
                BOUNCE_TIME: 1.0
                TIME_LIMIT: 300  # seconds
                ALARM_SPACING: 300  # seconds
                ALARM_INC_ADD: 0  # seconds
                ALARM_INC_MULT: 2
        ONE_CAR:
            CLOSED:
                NUMBER: 13
                PULL_UP: True
                BOUNCE_TIME: 1.0
            OPEN:
                NUMBER: 0
                PULL_UP: True
                BOUNCE_TIME: 1.0
                TIME_LIMIT: 600  # seconds
                ALARM_SPACING: 5  # seconds
                ALARM_INC_ADD: 0  # seconds
                ALARM_INC_MULT: 2

dev:
    BLANK: 0
