

base:
    APP:  # Window Start-up

    LOGGING:
        CONFIG_PATH: "configs/logging_config.yaml"

    SENSOR_GPIO_PINS:
        TWO_CAR:
            CLOSED:
                NUMBER: 4
                PULL_UP: True
                BOUNCE_TIME: 1
            OPEN:
                NUMBER: 17
                PULL_UP: True
                BOUNCE_TIME: 1
        ONE_CAR:
            CLOSE:
                NUMBER: 27
                PULL_UP: True
                BOUNCE_TIME: 1
            OPEN:
                NUMBER: 22
                PULL_UP: True
                BOUNCE_TIME: 1

dev:
    BLANK: 0